# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c36d17a17fb6c76c0dc372ee30c001743db79a405701e160c3ab041a9e3a7133fc2845e8813f2b4c318ccb32e9c81097a386ac07dc9252a5e1edb843f642319

test:
  secret_key_base: e4360add33c2430c97dbd37c3dcd4b5d45ae620dc67d66452dcf56668e9d4d2e7fefb0013a508ca8ebd84b54fd78da4077984ff323c7703ff67b2b2b72e126f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
